version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.48
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik
      - LOG_ALL_EVENTS=true
      - WORKSPACE_MOUNT_PATH=/opt/workspace_base
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openhands-data:/.openhands
      - workspace-data:/opt/workspace_base
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - openhands-network

volumes:
  openhands-data:
    driver: local
  workspace-data:
    driver: local

networks:
  openhands-network:
    driver: bridge